---
name: Super Code Linter


on:
  workflow_dispatch:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Super Code Linter
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Super Code Linter
        uses: github/super-linter@v4.9.7
        env:
          ACTIONS_RUNNER_DEBUG: true
          VALIDATE_ALL_CODEBASE: false
          ERROR_ON_MISSING_EXEC_BIT: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
